name: barcode_scanner_kit
description: Barcode scanner
version: 1.0.1
homepage: https://github.com/MarioJunio/flutter-barcode-scanner-plugin

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.google_ml_kit
        pluginClass: GoogleMlKitPlugin
      ios:
        pluginClass: GoogleMlKitPlugin
